### ISSUE TITLE
Reduce Solib's bundle size

### ISSUE THREAD

**Issue by devceline** [WalletConnect/solib#12]
Solib's bundle size is quiet big due to its dependency on `@solana/web3js` and our universal provider, among other factors. 

We need to find ways to decrease the bundlesize. One option would be making `@walletconnect/universal-provider` and `@solana/web3js` `peerDependencies` instead of direct dependencies.  This is similar to wagmi demanding an install of `ethers` alongside its main package.

However, with the way `solib` was written to not depend on the big utilities of `@solana/web3js`, we might be able to consider not using it all together. The biggest blocker of this is implementing `PublicKey` since it's the main struct we depend on.

This issue DOD is:
- Make a plan on how to reduce bundle size
- Implement it

**Comment by xzilja** [comment]
1. Definitely make `@solana/web3js` external peer dependency (non-optional)
2. Is `@walletconnect/qrcode-modal` needed?
3. Let's see if we can keep walletconnect universal provider in, but potentially can also become a separate peerDep
4. We can probably win a few kb with using rollup v3 without vite

**Comment by devceline** [comment]
> 1. Definitely make `@solana/web3js` external peer dependency (non-optional)
> 
>     2. Is `@walletconnect/qrcode-modal` needed?
> 
>     3. Let's see if we can keep walletconnect universal provider in, but potentially can also become a separate peerDep
> 
>     4. We can probably win a few kb with using rollup v3 without vite

Great input

1. I agree with you here.
2. It's "needed" to enable solib use outside web3modal. But possibly, could make qrcode an optional peer dep? So for web3modal where qrcode won't be used, they wouldn't need the extra weight
3. It's definitely needed for people using walletconnect, but there is the chance that someone might use `solib` without walletconnect connector. We'll wait on community feedback and usage for this.
4. I'll look into that

**Comment by devceline** [comment]
Assigning to myself, going to follow the following plan:

1. Make @solana/webjs optional dep
2. Make @walletconnect/qrcode optional dep
3. Possibly replace vite with rollup v3.

**Comment by xzilja** [comment]
You could try and also experiment with new standalone mode in web3modal, I think it might be a bit more lightweight compared to qrcode dependency and will look nicer. There is small example here

https://github.com/WalletConnect/web3modal/blob/V2/examples/react-standalone/src/pages/index.tsx

**Comment by devceline** [comment]
> You could try and also experiment with new standalone mode in web3modal, I think it might be a bit more lightweight compared to qrcode dependency and will look nicer. There is small example here
> 
> https://github.com/WalletConnect/web3modal/blob/V2/examples/react-standalone/src/pages/index.tsx

In that case, definitely an optional dep.

**Comment by devceline** [comment]
Closed with https://github.com/WalletConnect/solib/pull/13
